string='AATCCGTAAGAATCCGTAAGGCTACTTAAATCCGTAAGGTGCAGATTTGATCCAGGCTACTTATTGATCCAGGTGCAGATGCTACTTATTGATCCAGTGGACTTGCAGTGCAGATAATCCGTAAGTGGACTTGCAGCTACTTATGGACTTGCATTGATCCAGGTGCAGATTGGACTTGCATGGACTTGCATTGATCCAGAATCCGTAAGTGGACTTGCATTGATCCAGGTGCAGATTTGATCCAGGCTACTTAGCTACTTAAATCCGTAAGTGGACTTGCAGCTACTTATTGATCCAGGTGCAGATTGGACTTGCATGGACTTGCATGGACTTGCAGCTACTTAGCTACTTAGTGCAGATGTGCAGATGCTACTTATTGATCCAGGTGCAGATGTGCAGATTGGACTTGCATGGACTTGCAGCTACTTAGCTACTTAAATCCGTAAGGCTACTTAGTGCAGATAATCCGTAAGGCTACTTATGGACTTGCAAATCCGTAAGGTGCAGATGTGCAGATTTGATCCAGTTGATCCAGGTGCAGATAATCCGTAAGGCTACTTAGTGCAGATAATCCGTAAGAATCCGTAAGGTGCAGATGTGCAGATTGGACTTGCAGTGCAGATGTGCAGATAATCCGTAAGGCTACTTAAATCCGTAAGTGGACTTGCAGTGCAGATAATCCGTAAGGCTACTTAGTGCAGATTTGATCCAGGTGCAGATTGGACTTGCATGGACTTGCATTGATCCAGGTGCAGATGTGCAGATGTGCAGATGCTACTTATGGACTTGCAGCTACTTATTGATCCAGTTGATCCAGGTGCAGATAATCCGTAAGGTGCAGATTTGATCCAGTTGATCCAGGCTACTTATTGATCCAGTTGATCCAGGTGCAGATTTGATCCAGGCTACTTAAATCCGTAAGTTGATCCAGAATCCGTAAGGTGCAGATGTGCAGATAATCCGTAAG'
k=14


def most_freq_kmer(string, k):
	count={}
	for i in range(len(string)-k+1):
		substring=string[i:i+k]
		count[substring]=count.get(substring,0)+1

	cur_max=0
	output=[]
	for k,v in count.items():
		if v > cur_max:
			cur_max=v

	for k,v in count.items():
		if v==cur_max:
			output.append(k)
	return output

x=most_freq_kmer(string,k)
[print(y, end=' ') for y in x]