#!/usr/bin/env python3

seq="TCTGGCGTCAATTTGCCACGTTAACCCTGCATGACTCTCACAGTGAGCGGCAACAGTTCAGAAATTATAAGGCGCGGAGTTCAGATTTGACATATTATGTGGTTATATTCGGGTCCTGCTCTTGACGGAAGATACACGACTCTTAGGGTATGGTTTCAAATACGCACTCAGTTGGACAGCAATGTACTTACATGGCGCATTGCACTGGCTCCTAGGCCCGTGGCGCTACTTCAACGGGGTTGATACGGTACTCACGATTAGTCGGAACATCCCGGCGGCTAATGGTGGCGTCTAAGTCGTATCGTCGTCATCGCAAGTGCATCTTCTTGAAAATGACCCTCTATCTTACACGAGCCGGAGAAAAAAGTTAAGTCTTCATACGGTTATTCTTGTGCTGTCAGGCTCACAAGCCTACCCCGTAAAAGACCTGTATGCCATATCAATTGCTACCCTGCCGACATTGTCTACACGCTCAAAGACGGCGAAAATTAATCCTACGTAACTAGCCCACAAGGCCCTGGCAGGAGAGCGAACGTATTTCGACGAAATCGCAACGACTCTACGGTCGAGTGAATGCTCTTAACTCGTAGACCTGCACCGTTAACCTGGTGAGCACACACTCCTTTTATTCTTCCCTGCTGTCTGGCAGGTAGATCTCATTCAGTCCCTGCTCTTGTACTTATATCGTCGCAGGGTTAGCCTGGAGAGTCAATGGTGGCTCAGGACCTCTGTGATCCTGTTTATGGTTCACTACGACTCTGTTAGGTAAGGGGTACTAATGAGAAACTTTGCTTGAGTACAAAATGCATCGAGTCGGGCAAATTTAAAACGCGCCTTACTCTACGCTGCGGTTCACTGTCCGTCCGTGATTTATGCTAGACTTGACTAACTGGTCAATCTCTCATATGTAGGTAGCAGTAGGGCTATGCTCTCAGCCGCGATAAATGCGTAGGATCA"

def transcribe(seq):
    tmp=""
    for i in seq:
        if i == "T":
            tmp += "U"
        else:
            tmp += i
    return tmp
def main():
    rna = transcribe(seq)
    print(rna)

if __name__ == "__main__":
    main()
