#!/usr/bin/env python
# coding: utf-8

# In[3]:


seq = "CACGCTCAATATTCAATATCTCAATATTAGTCAATATTACTCAATATAAGATCTGTCAATATAGCTATCAATATTCAATATATCAATATTCAATATTCAATATTCAATATCCGTCAATATTTATCAATATTGATGTCTAATCAATATGGCGTCAATATGATTCTCAATATTCAATATACAGTCAATATGTTCCTCAATATATGTCAATATAAACGTCAATATTCAATATGCGCTCAATAAGTCCGATCAATATCCATGCTCAATATTCAATATCGCTCAATATCTCAATATTCAATATTCAATATCTCAATATTCAATATTCAATATCTCAATATCGTTCAATATCTTCAATATGTCAATATGCGTCAATATCTGTTCAATATTATCAATATTCAATATTATCAATATCGTCAATATCTCAATATTCCGTTGCGCTCAATATTTTCAATATTCAATATGCAACTCAATATGCTGCAGAAGGGATTCAATATTCAATATTTGACGATCAATATTCAATATTCTTTCAATATTTTCAATATTCAATATCTTCAATATGATTCAATATGATAGCGTCAATATGCCTCTACACTCAATATTCAGATCAATATTCTCTCAATATTGTCAATATAGAGAACGGGCTCAATATTCAATATTCAATATTCAATATTCAATATCTCAATATCTCAATATCTTCAATATTCAATATTCAATATTCAATATAACAGTCAATATATCAATATTCAATATATCAATATGTCAATATCTCAATATTCAATATTTACCTTTCAATATTGTCAATATTCAATATCGTTGATTGTCAATATTTCAATATTCAATATATCAATATGGTCAATATCTTTTTCAATATTTTCAATATGTGTTCAATATAAGTATGTGAACAACTTCAATATATATCAATATATCAATATTCAATATATTTCAATAT"
q = "TCAATATTC"


# In[9]:


def main(seq, q):
    pos = []
    for i in range(len(seq)-len(q)):
        if (seq[i:len(q)+i]) == q:
            pos.append(i+1)
    return pos
    




